### ISSUE TITLE
The app must listen on a UNIX socket in /home/user/web/domain/nodeapp/app.sock

### ISSUE THREAD

**Issue by prasad7676** [logico-ar/vestacp-nodejs#1]
Thanks For Your Hard-work, Please guide me,  

which code  i need to put on that file (app.sock) and what change i need to do in my app.js?

any example of app.js would be great thanks in advance

**Comment by logico-dev** [comment]
The app.sock file is generated by NodeJS and used by NGINX to comunicate with your app. Here is a sample of a o a minimal web server (YMMV).

```

// content of index.js
const http = require('http')
const path = require('path')
var rootPath = path.normalize(__dirname + '/..')

const port = rootPath + '/app.sock'

const requestHandler = (request, response) => {
  console.log(request.url)
  response.end('Hello Node.js Server!')
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  if (err) {
    return console.log('something bad happened', err)
  }

  console.log(`server is listening on ${port}`)
})

```

**Comment by Lucksmith369** [comment]
` console.log(request.url)`

is not working you got everytime / as request.url do you know the problem?
